//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmiCanada.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImmigrationService
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> PermanentResident { get; set; }
        public string Fee { get; set; }
        public string Time { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Overview { get; set; }
        public string Description { get; set; }
        public string Base64Image1 { get; set; }
        public string Base64Image2 { get; set; }
        public string Base64Image3 { get; set; }
        public string Base64Image4 { get; set; }
        public string Base64Image5 { get; set; }
    
        public virtual PermanentResident PermanentResident1 { get; set; }
        public virtual State State1 { get; set; }
        public virtual ImmigrationServiceType ImmigrationServiceType { get; set; }
    }
}
