//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmiCanada.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Overview { get; set; }
        public string Description { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> NumberOfView { get; set; }
        public Nullable<int> NumberOfLike { get; set; }
        public string RelationshipKeyword { get; set; }
        public string Base64Image { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsOutstanding { get; set; }
    
        public virtual Creator Creator1 { get; set; }
    }
}
