//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmiCanada.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorkId { get; set; }
        public Nullable<int> ImmigrationServiceId { get; set; }
        public Nullable<int> NocId { get; set; }
        public string Income { get; set; }
        public string Experience { get; set; }
        public string Position { get; set; }
        public string Certificate { get; set; }
        public string WorkType { get; set; }
        public Nullable<int> NumberOfRecruitments { get; set; }
        public string Sex { get; set; }
        public string Occupation { get; set; }
        public string Age { get; set; }
        public string Detail { get; set; }
        public string Benefic { get; set; }
        public Nullable<int> NumberOfView { get; set; }
        public string Base64Image { get; set; }
        public string Title { get; set; }
        public string Language { get; set; }
        public string WorkNumber { get; set; }
    
        public virtual ImmigrationService ImmigrationService { get; set; }
        public virtual Noc Noc { get; set; }
    }
}
